export { default as Home } from "./Home"
export { default as GetStarted } from "./GetStarted"
export { default as JoinUs } from "./JoinUs"
export { default as Login } from "./Login"
export { default as Waiting } from "./Waiting"
